engines:
  duplication:
    enabled: false
    config:
      languages: -javascript
  eslint:
    enabled: true
    checks:
      similar-code:
        enabled: true

exclude_patterns:
  - "node_modules/"
  - ".nyc_output"
  - "coverage"
  - "./*.test.js"