# .github/workflows/load-test.yml
name: Performance Tests

concurrency: 
  group: perf-${{ github.head_ref }}
  cancel-in-progress: true

on:
  schedule:
    # * is a special character in YAML, so you have to quote this string
    - cron: '*/15 * * * *'


loadTest:
  name: LoadTest
  runs-on: ubuntu-latest
  container: docker://loadimpact/k6:latest

  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Tests
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
      run: k6 cloud perf/load_test.js

